train:
    model_class: 
        name: mnist_models.RidgeClassifierMNIST
        kwargs:
            num_classes: 2
    loss_function: 
        name: mnist_models.BinaryClassificationL2Loss
        #     optimizer:
        #         name: torch.optim.SGD
        #         kwargs:
        #             lr: 0.001
        #             momentum: 0.8
    optimizer:
        name: torch.optim.Adam
        kwargs:
            lr: 0.001
    lr_scheduler:
        name: torch.optim.lr_scheduler.StepLR
        kwargs:
            step_size: 10
            gamma: 0.1
    num_epochs: 30
    save_ckpt: True
    save_dir: ./mnist_binary_ckpt_v1
evaluate:
    model_class: 
        name: mnist_models.RidgeClassifierMNIST
        kwargs:
            num_classes: 2
    loss_function: 
        name: mnist_models.BinaryClassificationL2Loss
    ckpt:
        ridgeclassifier0: 
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier0_l2_adam0.001_ep30_bs10_s1009.pt
              seed: 1009
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier0_l2_adam0.001_ep30_bs10_s2003.pt
              seed: 2003
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier0_l2_adam0.001_ep30_bs10_s3001.pt
              seed: 3001
        ridgeclassifier1: 
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier1_l2_adam0.001_ep30_bs10_s1009.pt
              seed: 1009
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier1_l2_adam0.001_ep30_bs10_s2003.pt
              seed: 2003
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier1_l2_adam0.001_ep30_bs10_s3001.pt
              seed: 3001
        ridgeclassifier10: 
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier10_l2_adam0.001_ep30_bs10_s1009.pt
              seed: 1009
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier10_l2_adam0.001_ep30_bs10_s2003.pt
              seed: 2003
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier10_l2_adam0.001_ep30_bs10_s3001.pt
              seed: 3001
        ridgeclassifier100: 
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier100_l2_adam0.001_ep30_bs10_s1009.pt
              seed: 1009
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier100_l2_adam0.001_ep30_bs10_s2003.pt
              seed: 2003
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier100_l2_adam0.001_ep30_bs10_s3001.pt
              seed: 3001
        ridgeclassifier1000: 
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier1000_l2_adam0.001_ep30_bs10_s1009.pt
              seed: 1009
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier1000_l2_adam0.001_ep30_bs10_s2003.pt
              seed: 2003
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier1000_l2_adam0.001_ep30_bs10_s3001.pt
              seed: 3001
        ridgeclassifier10000: 
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier10000_l2_adam0.001_ep30_bs10_s1009.pt
              seed: 1009
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier10000_l2_adam0.001_ep30_bs10_s2003.pt
              seed: 2003
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier10000_l2_adam0.001_ep30_bs10_s3001.pt
              seed: 3001
        ridgeclassifier100000: 
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier100000_l2_adam0.001_ep30_bs10_s1009.pt
              seed: 1009
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier100000_l2_adam0.001_ep30_bs10_s2003.pt
              seed: 2003
            - ckpt_path: ./mnist_binary_ckpt_v1/model_mnist_ridgeclassifier100000_l2_adam0.001_ep30_bs10_s3001.pt
              seed: 3001
    save_prediction: False
