dataset_id: mnist
train:
    image_directory: ./mnist/train-images-idx3-ubyte
    label_directory: ./mnist/train-labels-idx1-ubyte
    dataset_class: 
        name: mnist_data.MNISTDataset
        kwargs:
             label_map: {0: 0, 1: 1, 2: 0, 3: 1, 4: 0, 5: 1, 6: 0, 7: 1, 8: 0, 9: 1}
    num_classes: 2
    split:
        begin: 0
        num_samples: 50000
    transform:
        - name: torchvision.transforms.ToPILImage
        - name: torchvision.transforms.Resize
          kwargs:
              size: 75
        - name: torchvision.transforms.ToTensor
        - name: torchvision.transforms.Normalize
          kwargs:
              mean: [0.0]
              std: [255.0]
    batch_size: 10
    shuffle: True
val:
    image_directory: ./mnist/train-images-idx3-ubyte
    label_directory: ./mnist/train-labels-idx1-ubyte
    dataset_class: 
        name: mnist_data.MNISTDataset
        kwargs:
             label_map: {0: 0, 1: 1, 2: 0, 3: 1, 4: 0, 5: 1, 6: 0, 7: 1, 8: 0, 9: 1}
    num_classes: 2
    split:
        begin: 50000
        num_samples: 10000
    transform:
        - name: torchvision.transforms.ToPILImage
        - name: torchvision.transforms.Resize
          kwargs:
              size: 75
        - name: torchvision.transforms.ToTensor
        - name: torchvision.transforms.Normalize
          kwargs:
              mean: [0.0]
              std: [255.0]
    batch_size: 10
    shuffle: False
test:
    image_directory: ./mnist/t10k-images-idx3-ubyte
    label_directory: ./mnist/t10k-labels-idx1-ubyte
    dataset_class: 
        name: mnist_data.MNISTDataset
        kwargs:
             label_map: {0: 0, 1: 1, 2: 0, 3: 1, 4: 0, 5: 1, 6: 0, 7: 1, 8: 0, 9: 1}
    num_classes: 2
    split:
        begin: 0
        num_samples: 10000
    transform:
        - name: torchvision.transforms.ToPILImage
        - name: torchvision.transforms.Resize
          kwargs:
              size: 75
        - name: torchvision.transforms.ToTensor
        - name: torchvision.transforms.Normalize
          kwargs:
              mean: [0.0]
              std: [255.0]
    batch_size: 10
    shuffle: False
